dist: trusty
sudo: required
language: generic
env:
  global:
  - secure: "JGjIWN90hmoBKfYALsnFYVOtvkSkJ9yLUJaXTuN1HI24UOCTxw+dVg6FCneIu/P2f1UYXj7S7+9Zz5mqaZKDqa71G8oehoKj99OfQ7jog2sD532uxn7Ek5GqqjnVl/ELGukMiEZJOWQoReUAanp/8j4H4am3JcpnXTN4GnZduAhC+ZsgUjuxA87f+B0B2RvgCLsup2KjIu//Wzyvwqa6Bh7tGmkT7EEKK5Sdhg6a5CBkODxDZfZK+FdMO4B3cr260y/d6jhGjuLwNsZfZ4h3sCJHdk4FrpB1mjicoDyVdgqR1i4wRoRzUsxuKy1fmSyheL4gUp4yTKq4SW9pAkPiC4LKOKvDLjdag0o8D2Mirv+KLLFvDv1J/Fh95m+Z9QY3TiQ6riWzh/jJV5Wwrh5ukuhhSk05RVZADhC+BHV0ZPgdSHmS0oaX/usqfigMvTrmKkos5IPR03TX1toHUs8j1MwZPmxpUQz3fBScdnvLS1EH4/qUPcOQLuC+4tEFAMszlsSnW2AqI5iGIdU0AgkCbkbWs6o9WABlea3OpF0DaoDLzjmNvJ/lmFAUJBGntR9hIPBrjTcBb7iQN0EC5/CccbppRxHzazuPhmTKM16Mx4lT29pLQMYFeUhMG8et7VgQkD8hqdSHtXqGh0BhQN3eRblu57iyq87O85dBH3UE0B8="

addons:
  coverity_scan:
    project:
      name: "johntfoster/PUFfRS"
      description: "A Partition-of-Unity Framework for Reservoir Simulation"
    notification_email: jfoster@austin.utexas.edu
    build_command_prepend: "mkdir build; cd build; cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_Trilinos:BOOL=ON -DCMAKE_INSTALL_PREFIX=$HOME .."
    build_command: "make -j4"
    branch_pattern: coverity_scan

matrix:
  include:
  - if: branch = master
    os: linux
    before_install: 
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get -qq update
      - sudo apt-get install gcc-snapshot
      - sudo apt-get install -y g++-5
      - sudo apt-get install -y lcov
      - sudo apt-get install -y libblas-dev
      - sudo apt-get install -y liblapack-dev
      - sudo apt-get install -y libboost-dev
      - sudo apt-get install -y libyaml-cpp0.5
      - sudo apt-get install -y libyaml-cpp-dev
      - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh
      - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
      - mkdir build
      - cd build
      - sudo cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_Trilinos:BOOL=ON -DCMAKE_INSTALL_PREFIX=$HOME -DCOVERAGE:BOOL=ON -DBUILD_ALL_TPS=ON .. 
      - sudo make -j4
    script: sudo ctest
    after_success: 
      - gem install coveralls-lcov
      - make coverage
      - coveralls-lcov coverage.info.cleaned

  - if: branch = coverity_scan
    os: linux
    before_script:
      - sudo apt-get -qq update
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - sudo apt-get install -y g++-5
      - sudo apt-get install -y lcov
      - sudo apt-get install -y libblas-dev
      - sudo apt-get install -y liblapack-dev
      - sudo apt-get install -y libboost-dev
      - sudo apt-get install -y libyaml-cpp0.5
      - sudo apt-get install -y libyaml-cpp-dev
    before_install: echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
